## Pandas - Daataframe And Series

Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A series is a 1-D array-like object, while a DataaFrame is a 2-Dimensional, size mutable and potentially heterogeneous tablular data structures with labeled axes (rows and columns)

In [1]:
!pip install pandas
import pandas as pd

Collecting pandas
  Downloading pandas-2.3.3-cp310-cp310-macosx_11_0_arm64.whl.metadata (91 kB)
Requirement already satisfied: numpy>=1.22.4 in /Users/nik/Desktop/Nikhilesh/Machine Learning Course/01-Python/Python/venv/lib/python3.10/site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/nik/Desktop/Nikhilesh/Machine Learning Course/01-Python/Python/venv/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /Users/nik/Desktop/Nikhilesh/Machine Learning Course/01-Python/Python/venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp310-cp310-macosx_11_0_arm64.whl (10.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 4.9 MB/s  0:00:02 eta 0:00:01
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [pandas]2m2/3 [pandas]
Successfully installed pandas-2.3.3 pytz-2025.2 tzdata-2025.2

In [ ]:
## Series
## A pandas series is a one dimensional arrat-like object that can hold various data types. It is similar to a column in a table

data=[1,2,3,4,5]
series=pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
## Create a series from dictionary
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [4]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [10]:
## Dataframe - Multiple rows and columns

## create a dataframe from dictionary of list
data={
    'Name':['Arteta','Emery','Wenger'],
    'Age':[42,50,71],
    'City':['London','Manchester','Paris']
}
df=pd.DataFrame(data)
print(df)   
print(type(df))

     Name  Age        City
0  Arteta   42      London
1   Emery   50  Manchester
2  Wenger   71       Paris
<class 'pandas.core.frame.DataFrame'>

In [7]:
import numpy as np
np.array(df)

array([['Arteta', 42, 'London'],
       ['Emery', 50, 'Manchester'],
       ['Wenger', 71, 'Paris']], dtype=object)

In [9]:
## Create a Data frame from a list of dictionaries

data=[
    {'Name':'Arteta','Age':42,'City':'London'},
    {'Name':'Emery','Age':50,'City':'Manchester'},
    {'Name':'Wenger','Age':71,'City':'Paris'},
    {'Name':'Graham','Age':92,'City':'London'}

]

df=pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age        City
0  Arteta   42      London
1   Emery   50  Manchester
2  Wenger   71       Paris
3  Graham   92      London
<class 'pandas.core.frame.DataFrame'>

In [11]:
## Accessing Data From Dataframe
data

{'Name': ['Arteta', 'Emery', 'Wenger'],
 'Age': [42, 50, 71],
 'City': ['London', 'Manchester', 'Paris']}

In [12]:
df=pd.DataFrame(data)
df['Name']  # Accessing a single column

0    Arteta
1     Emery
2    Wenger
Name: Name, dtype: object

In [13]:
type(df['Name'])

pandas.core.series.Series

In [14]:
df.loc[0]

Name    Arteta
Age         42
City    London
Name: 0, dtype: object

In [15]:
df.iloc[0]

Name    Arteta
Age         42
City    London
Name: 0, dtype: object

In [16]:
df.loc[0][0]

/var/folders/rc/70_txq314mgdrwgpgqdw64cr0000gn/T/ipykernel_40507/2527876973.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0]

'Arteta'

In [17]:
df.iloc[0][0]

/var/folders/rc/70_txq314mgdrwgpgqdw64cr0000gn/T/ipykernel_40507/2900375399.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][0]

'Arteta'

In [18]:
## Accessing a specific element
df.at[2,'Age']

np.int64(71)

In [19]:
### Data manipulation with Dataframe
df

     Name  Age        City
0  Arteta   42      London
1   Emery   50  Manchester
2  Wenger   71       Paris

In [20]:
df['Salary']=[50000,60000,70000]

In [21]:
df

     Name  Age        City  Salary
0  Arteta   42      London   50000
1   Emery   50  Manchester   60000
2  Wenger   71       Paris   70000

In [22]:
## Remove a column
df.drop('Salary',axis=1)

     Name  Age        City
0  Arteta   42      London
1   Emery   50  Manchester
2  Wenger   71       Paris

In [23]:
df

     Name  Age        City  Salary
0  Arteta   42      London   50000
1   Emery   50  Manchester   60000
2  Wenger   71       Paris   70000

In [24]:
df.drop('Salary',axis=1,inplace=True)

In [25]:
df.describe()

             Age
count   3.000000
mean   54.333333
std    14.977761
min    42.000000
25%    46.000000
50%    50.000000
75%    60.500000
max    71.000000